# Generated by Django 4.1.2 on 2022-10-23 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medishopAppApi', '0002_remove_cart_ativo_remove_cart_uni_id_cart_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medishopAppApi.usuario'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantidade',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
