# Generated by Django 4.1.2 on 2022-10-23 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medishopAppApi', '0003_alter_cart_user_alter_cartitem_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medishopAppApi.usuario'),
        ),
    ]
