# Generated by Django 4.1.2 on 2022-10-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medishopAppApi', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='a', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='logradouro',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
